[package]
name = "ssh-multi"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.43", features = ["derive"] }
nix = { version = "0.30.1", features = ["socket", "net", "uio"] }
rayon = "1.10.0"
