[package]
name = "sshmulti"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
nix = { version = "0.30.1", features = ["socket", "net", "uio"] }
rayon = "1.10.0"
