name: build
on:
    workflow_dispatch:

jobs:
    build_linux:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: Build
              run: |
                  rustup target  add x86_64-unknown-linux-musl
                  cargo build --release --target x86_64-unknown-linux-musl

            - name: Upload binary
              uses: actions/upload-artifact@v4
              with:
                  name: ssh-multi-linux
                  path: target/x86_64-unknown-linux-musl/release/ssh-multi

    build_macos:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: Build
              run: |
                  cargo build --release

            - name: Upload binary
              uses: actions/upload-artifact@v4
              with:
                  name: ssh-multi-macos
                  path: target/release/ssh-multi
